mdt_app/__init__.py
"""
MDT app

Creates app and sets all of the functionality of the application for users.
manage.py creates the app using this module (with settings in config.py)

Decorators and models are not blueprint specific.
Forms and views are blueprint specific so are divided by admin, auth and main.
"""

from flask import Flask, render_template

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_login import LoginManager, current_user
from flask_admin import Admin

from config import config
from mdt_app.admin.views import (AdminModelView, CustomAdminModelView,
                                 MyAdminIndexView)

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
db = SQLAlchemy()


def create_app(config_name):
    global db
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)

    admin = Admin(template_mode='bootstrap3',
                  index_view=MyAdminIndexView())
    admin.init_app(app)
    admin.add_view(CustomAdminModelView(User, db.session))
    admin.add_view(AdminModelView(Patient, db.session))
    admin.add_view(AdminModelView(Meeting, db.session))
    admin.add_view(AdminModelView(Case, db.session))
    admin.add_view(AdminModelView(Action, db.session))
    admin.add_view(AdminModelView(Attendee, db.session))

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

# placed at end to avoid circular argument
from mdt_app.models import User, Case, Meeting, Action, Patient, Attendee

mdt_app/admin/__init__.py
"""
Admin module is mostly handled in the mdt_app __init__

Here custom admin views are defined in views.py
"""

mdt_app/admin/views.py
from flask import abort
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user


class AdminModelView(ModelView):
    """Model view, must be admin to access"""
    page_size = 50  # the number of entries to display on the list view

    def is_accessible(self):
        if current_user.is_anonymous:
            return False
        else:
            return current_user.is_admin

    def inaccessible_callback(self, name, **kwargs):
        abort(403)


class MyAdminIndexView(AdminIndexView):
    """Index view, must be admin to access"""
    def is_accessible(self):
        if current_user.is_anonymous:
            return False
        else:
            return current_user.is_admin

    def inaccessible_callback(self, name, **kwargs):
        abort(403)


class CustomAdminModelView(AdminModelView):
    """Custom list template to show unconfirmed users with a row in red"""
    list_template = 'admin/list.html'

mdt_app/main/__init__.py
"""
Main module is for all other views, forms and errors for the app that are not
administration of tables or user logins
"""
from flask import Blueprint

main = Blueprint('main', __name__)

# at end to avoid circular references
from . import views, errors

mdt_app/main/views.py
from datetime import date

from flask import render_template, redirect, request, url_for, flash, abort
from flask_login import login_required, current_user

from .. import db
from ..models import Case, Meeting, Patient, Action, Attendee, User
from . import main
from .forms import *


@main.route('/index')
def index():
    """Index page, link for users to change their own password"""
    return render_template('index.html', title='Welcome to the MDT App')


@main.route('/')
@main.route('/cases/',  methods=['GET', 'POST'])
@login_required
def case_list():
    """Returns cases, progress and attendee form

    Fairly bloated view but used for a lot of situations
    If meeting date request argument, generate attendee form and MDT progress
    otherwise set these to be null
    If push_cases, move undiscussed cases to next meeting
    For POST method, delete any attendees for meeting that are not in form
    add any new attendees.

    Request arguments:
    meeting -- date str: meeting date to filter by (e.g. 2017-09-20)
    push_cases -- if exists, push all undiscussed cases to next meeting


    Template variables:
    title -- title
    cases -- all cases (sorted by dec. meeting_date and inc. created_on)
    counts -- dictionary of total per status of cases, and percent complete
    attendee_form -- attendee form of all confirmed users
    attendees -- list of all attendee objects
    meeting -- meeting date
    """

    meeting_date = request.args.get('meeting')
    title = 'All cases'
    if meeting_date:
        meeting = Meeting.query.filter_by(date=meeting_date).first()
        case_query = Case.query.filter_by(meeting=meeting)
        attendees = Attendee.query.filter_by(meeting=meeting).all()
        attendee_list = [attendee.user for attendee in attendees]
        attendee_form = AttendeeForm(data={'user': attendee_list,
                                           'comment': meeting.comment})
        title = 'Meeting: {}'.format(meeting.date_repr)
        counts = {stat.lower(): (Case.query
                                     .filter_by(status=stat, meeting=meeting)
                                     .count())
                  for stat in
                  ['TBD', 'COMP', 'DISC']}
        # For a case to be complete, it must be discussed so add together
        case_count = len(case_query.all())
        if case_count:
            counts['percent_discussed'] = int(100 / case_count *
                                              (counts['disc'] + counts['comp']))
    else:
        case_query = Case.query
        attendee_form = None
        counts = None
        attendees = None
    cases = (case_query.join(Meeting)
                       .order_by(Meeting.date.desc(), Case.created_on)
                       .all())
    push_cases = request.args.get('push_cases')
    # Pick up submission from page
    if push_cases:
        # Push cases to next meeting
        next_meeting = (Meeting.query
                        .filter(Meeting.date > meeting_date,
                                Meeting.is_cancelled == False)
                        .order_by(Meeting.date)
                        .first())
        if not next_meeting:
            flash('Cases could not be pushed to next meeting, '
                  'no meetings exist after this one',
                  category='warning')
        else:
            for to_push in cases:
                if to_push.status == 'TBD':
                    if any(to_push.patient_id == next_meet_case.patient_id
                           for next_meet_case in next_meeting.cases):
                        flash(('Case for patient {f_name} {l_name} was not '
                               'moved as patient also has a case on {new_date}'
                               ).format(f_name=to_push.patient.first_name,
                                        l_name=to_push.patient.last_name,
                                        new_date=next_meeting.date_repr),
                              category='warning')
                    else:
                        to_push.meeting_id = next_meeting.id
                        flash(
                              ('Case for patient {f_name} {l_name} was moved '
                               'to {new_date}'
                               ).format(f_name=to_push.patient.first_name,
                                        l_name=to_push.patient.last_name,
                                        new_date=next_meeting.date_repr),
                              category='success')
            db.session.commit()
    elif attendee_form and attendee_form.validate_on_submit():
        # attendee_form not present if no filter by date
        meeting.comment = attendee_form.comment.data
        form_attendees = attendee_form.user.data
        for row_attendee in attendees:
            # remove users in database that are not in form data
            if not any(row_attendee.user.username == form_user.username
                       for form_user in form_attendees):
                db.session.delete(row_attendee)
        for form_user in form_attendees:
            # if form user not in database, add them
            if not any(form_user.username == row_attendee.user.username
                       for row_attendee in attendees):
                new_attendee = Attendee(meeting_id=meeting.id,
                                        user=form_user)
                db.session.add(new_attendee)
        db.session.commit()
        return redirect(url_for('main.case_list', meeting=meeting_date))
    return render_template('case_list.html', cases=cases, title=title,
                           counts=counts, attendee_form=attendee_form,
                           attendees=attendees, meeting=meeting_date)


@main.route('/cases/create/<patient_id>',  methods=['GET', 'POST'])
@login_required
def case_create(patient_id=None):
    """ Returns cases for patient and form to create new case for patient

    CaseCreateForm allows for selecting a meeting or entering one in manually
    Manually entered meeting date then creates this in the database.

    Request arguments:
    patient_id -- int: patient_id to filter by

    Template variables:
    title -- title
    cases -- all cases (filtered by patient)
    form -- case_create form
    patient_id -- patient id
    """

    patient = Patient.query.filter_by(id=patient_id).first()
    cases = (Case.query
                 .filter_by(patient_id=patient_id)
                 .join(Meeting)
                 .order_by(Meeting.date.desc())
                 .all())
    title = ('Cases for {f_name} {l_name} {hosp}'
             ).format(f_name=patient.first_name,
                      l_name=patient.last_name,
                      hosp=patient.hospital_number)
    flash('Date of birth (age): {age}'.format(age=patient.date_of_birth_repr),
          category='post-header')
    # set case_id to be -1 so that validation methods won't match by case_id
    form = CaseForm(patient_id=patient_id, case_id=-1)
    if form.validate_on_submit():
        if form.meeting.data:
            meeting_id = form.meeting.data.id
        else:
            new_date = Meeting(date=form.add_meeting.data,
                               comment='')
            db.session.add(new_date)
            db.session.commit()
            flash('MDT meeting added for {}'.format(new_date.date_repr),
                  category='success')
            added_meeting = (Meeting.query
                                    .filter_by(date=form.add_meeting.data)
                                    .first())
            meeting_id = added_meeting.id
        case = Case(meeting_id=meeting_id,
                    consultant_id=form.consultant.data.id,
                    patient_id=patient_id,
                    next_opa=form.next_opa.data,
                    clinic_code=form.clinic_code.data,
                    planned_surgery=form.planned_surgery.data,
                    surgery_date=form.surgery_date.data,
                    medical_history=form.medical_history.data,
                    mdt_vcmg=form.mdt_vcmg.data,
                    question=form.question.data,
                    created_on=date.today(),
                    created_by_id=current_user.id,
                    status='TBD')
        db.session.add(case)
        db.session.commit()
        flash(('New case added for {f_name} {l_name}'
               ).format(f_name=patient.first_name,
                        l_name=patient.last_name),
              category='success')
        return redirect(url_for('main.case_list'))
    return render_template('case_create.html', cases=cases, form=form,
                           patient_id=patient_id,
                           title=title)


@main.route('/cases/edit/<patient_id>/<case_id>',  methods=['GET', 'POST'])
@login_required
def case_edit(patient_id=None, case_id=None):
    """ List cases for patient and case edit form

    CaseEditForm is an extended version of the CaseCreateForm that has
    fields for the MDT process.

    Changes status of case as appropriate:
    - If no_actions in form is ticked, completes status
    - else if form doesn't have discussion filled, set to TBD (to be discussed)
    - else if form has new action - change to discussed

    When new action is added, saves and loads template scrolling down to
    the table position.

    Request arguments:
    patient_id -- int: patient id, required
    case_id --  int: case id, required

    Template variables:
    title -- str: title
    cases -- list: all case models for patient
    form -- form: CaseEditForm
    case -- model: current case being edited
    patient_id -- int: patient_id
    case_id -- int: case id
    """

    if not (patient_id and case_id):
        flash('Patient or case details not given', category='danger')
        return abort(404)
    patient = Patient.query.filter_by(id=patient_id).first()
    cases = (Case.query
                 .filter_by(patient_id=patient_id)

mdt_app/templates/_date_format.html
<br>
<t1> Dates are in the format DD-MMM-YYY.
<br>For example:
    <ul>
        <li> 21-Apr-2017 </li>
    </ul>
</t1>

mdt_app/templates/action_list.html
{% extends "base.html" %}

{% block page_content %}
	<div>
		{% if title != 'Actions ' %}
		<a href="{{ url_for('main.action_list') }}"
		   class="btn btn-default" role="button">View all actions</a>
		<br><br>
		{% endif %}
		<div class="table-responsive">
			<table id="unsorted" class="table">
				<thead>
					<tr>
						<th>Edit case</th>
						<th>Edit action</th>
						<th>Show actions for user</th>
						<th>Completed?</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% for action in actions %}
						{% if action.case.status == 'COMP' %}
							<tr class='alert alert-success'>
						{% elif action.is_completed %}
							<tr>
						{% else %}
							<tr class='alert alert-warning'>
						{% endif %}
						<td> <a href="{{ url_for('main.case_edit', case_id=action.case_id, patient_id=action.case.patient_id) }}" class="btn btn-primary"> {{action.case.patient.hospital_number}} {{action.case.patient.first_name}} {{action.case.patient.last_name}} </a> </td>
						<td> <a href="{{ url_for('main.action_edit', action_id=action.id, user_id=user_id) }}" class="btn btn-info">{{action.action|truncate(length=60)}} </a> </td>
						<td><a href="{{ url_for('main.action_list', user_id=action.assigned_to_id)}}">{{action.assigned_to.username}}</a></td>
						{% if action.is_completed %}
							<td>  Yes </td>
							<td></td>
						{% else %}
							<td>  No </td>
							<td> <a href="{{ url_for('main.action_list', action_id=action.id)}}" class="btn btn-default" role="button">Mark as complete</a> </td>
						{% endif %}
						</tr>
					{% endfor %}
			    </tbody>
			</table>
		</div>
		<div class="row">
			<div class="well well-warning col-sm-3">
				<strong>Action incomplete </strong>
			</div><div class="col-sm-1"></div>
			<div class="well well-white col-sm-3">
				<strong>Action complete</strong>
			</div><div class="col-sm-1"></div>
			<div class="well well-success col-sm-4">
				<strong>All actions complete for case</strong>
			</div>
		</div>
	</div>
{% endblock %}

mdt_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="MDT app for urodynamics">
		<meta name="author" content="Stef Piatek">
		<title>
			{% block title %}MDT - {{ title }} {% endblock %}
		</title>

		{% block head %}
		<link rel="icon" href="{{ url_for('static', filename ='favicon.ico') }}">
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
			<!--[if lt IE 9]>
			  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
			<![endif]-->
		{% endblock %}

		{% block styles %}
		<link rel="stylesheet" href="{{url_for('static', filename='datatables.min.css')}}"></link>
		<link rel="stylesheet" href="{{url_for('static', filename='fixes/ie10-viewport-bug-workaround.css')}}"></link>
		<link rel="stylesheet" href="{{url_for('static', filename='bootstrap-datepicker-1.6.4/css/bootstrap-datepicker.min.css')}}"></link>


		<style>
			.required {
				font-weight: bold;
				color: #207720; }
				body { padding-top: 60px;
				}
			td.whitespace {
				white-space: pre-wrap;
				}
			.well-warning{
				color: #8a6d3b;
				background:  #fcf8e3 !important;
				}
			.well-success{
				color: #3c763d;
				background: #dff0d8 !important;
				}
			.well-white{
				background-color: #FDFDFD;
				}
		</style>
		{% endblock %}
	</head>

	<body>
		{% block navbar %}
		<div class="navbar navbar-default navbar-fixed-top">
			<div class="container-fixed">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
						<a class="navbar-brand" href="{{ url_for('main.index') }}">MDT</a>
				  </div>
				<div class="collapse navbar-collapse">
					<ul class="nav nav-pills navbar-static-top">
						<li><a href="{{ url_for('main.case_list') }}">All cases</a></li>
						<li><a href="{{ url_for('main.meeting_list') }}">Meetings</a></li>
						<li><a href="{{ url_for('main.patient_list') }}">Patients</a></li>
						<li><a href="{{ url_for('main.action_list', user_id=current_user.id) }}">View my actions</a></li>
						{% if current_user.is_authenticated %}
							<li class = "navbar-right"><a href="{{ url_for('auth.logout') }}">Logout</a></li>
							<li class="navbar-text navbar-right">Welcome {{ current_user.f_name }} {{ current_user.l_name }}</li>
							{% if current_user.is_admin %}
						   	    <li class = "navbar-right dropdown">
								    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
								    <ul class="dropdown-menu">
									    <li><a href="{{ url_for('auth.reset_password') }}">Reset passwords</a></li>
									    <li><a target="_blank" href="/admin">Admin site</a></li>
								    </ul>
							    </li>
							{% endif %}
						{% else %}
							<li class = "navbar-right"><a href="{{ url_for('auth.login') }}">Login</a></li>
						{% endif %}
					</ul>
				</div><!--/.nav-collapse -->
			</div><!--/.container-fluid -->
		</div>
		{% endblock %}

		{% block content %}
			<div class="container-fluid">
				<div class="row-fluid">
					<div class="span12">
						<div class="page-header">
							<h1> {{ title }} </h1>
						</div>
						{% with messages = get_flashed_messages(with_categories=True) %}
							{% for message in messages %}
								{% if message[0] == 'post-header' %}
									<h4> {{ message[1] }} </h4>
									<br>
								{% else %}
									<div class="alert alert-{{ message[0] }}">{{ message[1] }} </div>
								{% endif %}
							{% endfor %}
							{% if form %}
								{% if form.errors %}
									<div class="alert alert-danger"> Errors in form </div>
								{% endif %}
							{% endif %}
						{% endwith %}
					</div>
				</div>
				{% block page_content %}{% endblock %}
			</div>
		{% endblock %}

		{% block scripts %}
			<!-- datatables contains bootstrap3 and jquery 1.12-->
			<script type="text/javascript" src="{{url_for('static', filename='datatables.min.js') }}"></script>
			<script type="text/javascript" src="{{url_for('static', filename='bootstrap-datepicker-1.6.4/js/bootstrap-datepicker.min.js') }}"></script>
			<script type="text/javascript" charset="utf-8">
				$(document).ready(function(){
					$('#datatable').dataTable({
						"paging": false,
						"order": [0, "desc"]
						});
					});
				$(document).ready(function(){
					$('#unsorted').dataTable({
						"iDisplayLength": 25,
						"aaSorting": []
						});
					});
				$(document).ready(function(){
					$('#basic_dt').dataTable({
						"aaSorting": [],
						"paging": false,
						});
					});
				$(document).ready(function(){
				    $('.input-group.date').datepicker({
					    format: "dd-M-yyyy",
					    weekStart: 1,
					    todayBtn: "linked",
					    daysOfWeekDisabled: "0,6",
					    todayHighlight: true
					});
				});
			<!-- use scroll='element' to load a page on a particular element-->
			{% if scroll %}
				document.location.hash = '#' + '{{ scroll }}';
			{% endif %}
			</script>
			<script rel="stylesheet" src="{{url_for('static', filename='fixes/ie10-viewport-bug-workaround.js') }}"></script>

		{% endblock %}
	</body>

</html>

mdt_app/templates/case_create.html
{% extends "case_list.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    {{ super() }}
	<br>
	<div class="panel panel-default">
		<div class="panel-heading"><h3>Create case</h3></div>
		<div class="panel-body">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h4>Case details</h4>
						<form method="POST" action="{{ url_for('main.case_create',
												   patient_id=patient_id) }}">
							<table class ="table table-condensed" width="100%" cellspacing="0">
								<!-- creates cells for form -->
								{% include "_case_details_form.html" %}
								<input style="float:right" type="submit" value="Create case">
							</table>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

mdt_app/templates/case_edit.html
{% import "bootstrap/wtf.html" as wtf %}
{% from "_form_helpers.html" import render_field, render_label, render_input %}
{% extends "case_list.html" %}

{% block page_content %}
    {{ super() }}
	<br>
	<div class="panel panel-default">
		<div class="panel-heading"><h3>Edit case</h3></div>
		<div class="panel-body">
			<div class="container">
				<div class="row">
					<form method="POST" action="{{ url_for('main.case_edit',
											   case_id=case_id,
											   patient_id=patient_id) }}">
						<div class=" col-sm-6" style="overflow:scroll">
							<h4>Case details</h4>
							<table class ="table table-condensed" width="100%" cellspacing="0">
								<!-- creates cells for form -->
								{% include "_case_details_form.html" %}
							</table>	
						</div>
						<div class="col-sm-6" style="overflow:scroll">
							<h4>Outcome of meeting</h4>
							<table id="discussion" class ="table table-condensed" width="100%" cellspacing="0">
								<tr>
									<td>{{ form.discussion.label }}</td> 
									<td colspan=2>{{ form.discussion(rows=7, cols=60) }}</td>
								</tr>
								{% for action in case.actions %}
									{% if action.is_completed%}
										<tr class="alert-success">
									{% else %}							   
										<tr> 
									{% endif %}	
											<th> Saved action </th>
											<td><a href="{{ url_for('main.action_edit', user_id=action.assigned_to_id, action_id=action.id)}}">
												  {{ action.action }}</a></td>
											<td>{{ action.assigned_to.username }}</td>
										</tr>
								{% endfor %}
								<tr>
									{{ render_field(form.action, size=40) }} 
									<td>{{ render_input(form.action_to) }}</td>
								</tr>
								<tr> {{render_field(form.no_actions) }}</tr>
								<tr><td colspan=3><input style="float:right" type="submit" value="Update case"></td></tr>
							</table>
						</div>
					</form>	
				</div>	
			</div>	
		</div>
	</div>
{% endblock %}

mdt_app/templates/case_list.html
{% import "bootstrap/wtf.html" as wtf %}
{% from '_form_helpers.html' import render_input %}

{% extends "base.html" %}
{% block page_content %}
	{% if attendee_form %}
		<div class="panel panel-default">
			<div class="panel-heading"><h3>Members present at MDT</h3></div>
			<div class="panel-body">
				<form method="POST" action="{{ url_for('main.case_list', meeting=meeting) }}">
					<div class="row">
						{{ attendee_form.csrf_token }}
						<div class="col-sm-3">
							<br>
							{{ render_input(attendee_form.user, size=15) }}
						</div>
						<div class="col-sm-3">
							<strong>{{ attendee_form.comment.label }}</strong>
							{{ render_input(attendee_form.comment, rows=11, cols=20) }}
						</div>
						<div class="col-sm-1"></div>
						<div class="col-sm-3">
							<strong> Members added to meeting </strong>
							<ul>
								{% for attendee in attendees %}
									<li> {{ attendee.user.f_name }}  {{ attendee.user.l_name }} </li>
								{% endfor %}
							</ul>
						</div>
					</div>
					<div class="row">
						<input type="submit" value="Save MDT members and comments">
						<br><br>
						<p> Ctrl + click to select multiple members</p>
					</div>
				</form>
			</div>
		</div>
	{% endif %}
	{% if counts and cases %}
		<div class="panel panel-default">
			<div class="panel-heading"><h3>Progress</h3></div>
			<div class="panel-body">
				<div class="row">
					<div class="well well-white col-sm-3">
						<strong>To be discussed: {{ counts.tbd }} / {{ cases|count }}</strong>
					</div><div class="col-sm-1"></div>
					<div class="well well-warning col-sm-3">
						<strong>Discussed & to be actioned: {{ counts.disc }} / {{ cases|count }} </strong>
					</div><div class="col-sm-1"></div>
					<div class="well well-success col-sm-3">
						<strong>Discussed & actioned: {{ counts.comp }} / {{ cases|count }}</strong>
					</div>
				</div>
				<div class="progress">
					<div class="progress-bar progress-bar-info" role="progressbar"
						 aria-valuenow="{{ counts.percent_discussed }}"
						 aria-valuemin="0" aria-valuemax="100" style="width:{{ counts.percent_discussed }}%">
						 {{ counts.percent_discussed }}% Discussed
					</div>
				</div>
				<a href="{{ url_for('main.case_list', meeting=meeting, push_cases=True)}}"
				   class="btn btn-default" role="button">Push undiscussed cases to next meeting</a>
			</div>
		</div>
	{% else %}
		<div class="row">
			<div class="well well-white col-sm-3">
				<strong>To be discussed</strong>
			</div><div class="col-sm-1"></div>
			<div class="well well-warning col-sm-3">
				<strong>Discussed & to be actioned</strong>
			</div><div class="col-sm-1"></div>
			<div class="well well-success col-sm-3">
				<strong>Discussed & actioned</strong>
			</div>
		</div>
	{% endif %}
	<div class="panel panel-default">
		<div class="panel-heading"><h3>Overview of cases</h3></div>
		<div class="panel-body" style="overflow:scroll">
			<table id="unsorted" class="table" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Meeting Date</th>
						{% if not (form or counts) %}
							<th> </th>
						{% endif %}
						<th>Added by</th>
						{% if not form or form.patient_id %}
						<th>Edit Case</th>
						{% endif %}
						<th>Consultant</th>
						<th>Medical History</th>
						<th>Question for MDT</th>
						<th>Discussion</th>
						<th>Actions by</th>
					</tr>
				</thead>
				<tbody>
				{% for case in cases %}
					{% if case.status == 'COMP' %}
						<tr class="alert alert-success">
					{% elif case.status == 'DISC' %}
						<tr class="alert alert-warning">
					{% else %}
						<tr>
					{% endif %}
						<td> <a href="{{ url_for('main.case_list', meeting=case.meeting.date)}}">
							 {{ case.meeting.date_repr }} </a></td>
						{% if not (form or counts) %}
							<td> <a href="{{  url_for('main.case_create', patient_id=case.patient.id)}}"
									class="btn btn-default" role="button">Previous<br>cases</a>  </td>
						{% endif %}
						<td> {{case.created_by.f_name}} {{case.created_by.l_name}} </td>
						{% if not form or form.patient_id %}
						<td> <a href="{{ url_for('main.case_edit', patient_id=case.patient_id, case_id=case.id)}}" class="btn btn-primary">
								 {{case.patient.hospital_number}}<br>{{case.patient.first_name}}<br>
								 {{case.patient.last_name}}</a></td>
						{% endif %}
						<td> {{case.consultant.initials}} </td>
						<td class="whitespace">{{case.medical_history|truncate(length=120)}}</td>
						<td class="whitespace">{{case.question}}</td>
						<td class="whitespace">{{case.discussion}}</td>
						<td>
							{% for action in case.actions %}{% if action %}
								<a href="{{ url_for('main.action_list', user_id=action.assigned_to_id)}}"> {{ action.assigned_to.username }} </a>
								<br>
							{% endif %}{% endfor %}
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
        </div>
    </div>
{% endblock %}

mdt_app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
	{% if current_user.is_authenticated %}
		<p> You are logged in as {{ current_user.username }}
			<br><br>
			You can <a href="{{ url_for('auth.change_password') }}">change your password</a> if it has been reset.
		</p>
	{% else %}
		<p> Please <a href="{{ url_for('auth.login') }}">log in</a>
			or <a href="{{ url_for('auth.register') }}">register</a> to continue
		</p>
	{% endif %}
{% endblock %}